version: '2'
services:
   geoserver:
    image: kartoza/geoserver
    container_name: eosai_geoserver
    ports:
      - 9090:8080
    volumes:
      - ./data:/root/stores
      - ./geoserver_data_dir:/opt/geoserver/data_dir
      - ~/pkz029_UU_CMEMS_dockerized/shared_data:/shared
networks:
  default:
    external:
      name: cmems
